# Generated by Django 3.2.4 on 2021-06-06 09:26

from django.db import migrations, models
import django.db.models.deletion


def make_data(apps, schema_editor):
    Book = apps.get_model("core", "Book")
    Author = apps.get_model("core", "Author")

    author = Author.objects.create(name="Test author")
    Book.objects.create(title="Test title", author=author)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.author"
                    ),
                ),
            ],
        ),
        migrations.RunPython(make_data, reverse_code=migrations.RunPython.noop),
    ]
